version: "3.3"

services:
    mariadb:
        image: mariadb
        container_name: mariadb
        environment:
            - MYSQL_ROOT_PASSWORD=root

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        links:
            - mariadb:db
        ports:
            - "1995:80"

    wordpress:
        image: wordpress
        container_name: wordpress
        links:
            - mariadb:mysql
        ports:
            - "1992:80"
